"""Data export utilities for environmental data (CSV and PDF).

Both formats include a mandatory INPE data source attribution header
and the timestamp at which the data was collected.

Usage::

    from src.services.data_export import export_csv, export_pdf

    csv_bytes = export_csv(df, "queimadas_amazonia_2026-05.csv")
    st.download_button("Baixar CSV", csv_bytes, "queimadas.csv", "text/csv")

    pdf_bytes = export_pdf(fig, df, "relatorio_desmatamento.pdf")
    st.download_button("Baixar PDF", pdf_bytes, "relatorio.pdf", "application/pdf")
"""

from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any

import pandas as pd


# ------------------------------------------------------------------ #
# Attribution constants                                                 #
# ------------------------------------------------------------------ #

_ATTRIBUTION_LINES = [
    "# Fonte / Source: INPE — Instituto Nacional de Pesquisas Espaciais",
    "# Sistemas: DETER (terrabrasilis.dpi.inpe.br) | BDQueimadas (queimadas.dgi.inpe.br) | PRODES (obt.inpe.br/OBT/assuntos/programas/amazonia/prodes)",
    "# Licença / License: dados públicos INPE — uso livre com atribuição",
    "# Gerado por / Generated by: Environmental Status Tracker for Brazil",
]


def _attribution_block(fetched_at: datetime | None = None) -> list[str]:
    lines = list(_ATTRIBUTION_LINES)
    ts = fetched_at or datetime.now(timezone.utc)
    lines.append(f"# Coleta / Collection timestamp: {ts.strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("#")
    return lines


# ------------------------------------------------------------------ #
# CSV export                                                            #
# ------------------------------------------------------------------ #

def export_csv(
    data: pd.DataFrame | list[dict[str, Any]],
    filename: str = "inpe_data.csv",
    fetched_at: datetime | None = None,
    title: str | None = None,
) -> bytes:
    """Serialise *data* to UTF-8 CSV bytes with an INPE attribution header.

    Args:
        data:       DataFrame or list of dicts to export.
        filename:   Suggested download filename (used only for logging; caller
                    passes it to ``st.download_button``).
        fetched_at: When the underlying INPE data was fetched.  Defaults to
                    the current UTC time when omitted.
        title:      Optional one-line description written as a comment above
                    the attribution block.

    Returns:
        UTF-8-encoded bytes ready for ``st.download_button``.
    """
    if isinstance(data, list):
        df = pd.DataFrame(data)
    else:
        df = data.copy()

    buf = io.StringIO()

    if title:
        buf.write(f"# {title}\n")
    for line in _attribution_block(fetched_at):
        buf.write(line + "\n")

    df.to_csv(buf, index=False)
    return buf.getvalue().encode("utf-8")


# ------------------------------------------------------------------ #
# PDF export                                                            #
# ------------------------------------------------------------------ #

def export_pdf(
    chart: Any,          # plotly Figure
    data: pd.DataFrame | list[dict[str, Any]],
    filename: str = "inpe_report.pdf",
    title: str = "Relatório Ambiental / Environmental Report",
    fetched_at: datetime | None = None,
) -> bytes:
    """Render *chart* and *data* as a PDF byte stream with INPE attribution.

    Uses ``reportlab`` when available; falls back to a plain-text PDF
    containing only the attribution header and data table when reportlab
    is not installed.

    Args:
        chart:      Plotly Figure to embed as an image.  Pass ``None`` to
                    skip the chart section.
        data:       DataFrame or list of dicts for the data table section.
        filename:   Suggested download filename.
        title:      Report title printed at the top of the first page.
        fetched_at: Collection timestamp written into the attribution footer.

    Returns:
        PDF bytes ready for ``st.download_button``.
    """
    if isinstance(data, list):
        df = pd.DataFrame(data)
    else:
        df = data.copy()

    try:
        return _pdf_reportlab(chart, df, title, fetched_at)
    except ImportError:
        return _pdf_fallback(df, title, fetched_at)


# ------------------------------------------------------------------ #
# PDF — reportlab implementation                                        #
# ------------------------------------------------------------------ #

def _pdf_reportlab(
    chart: Any,
    df: pd.DataFrame,
    title: str,
    fetched_at: datetime | None,
) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
    )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=2*cm, rightMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Title"],
                                 fontSize=14, textColor=colors.HexColor("#1E7A4A"))
    body_style = styles["BodyText"]
    muted_style = ParagraphStyle("Muted", parent=body_style,
                                 fontSize=8, textColor=colors.HexColor("#6C757D"))

    story = []

    # Title
    story.append(Paragraph(title, title_style))
    story.append(Spacer(1, 0.4*cm))

    # Attribution block
    ts = fetched_at or datetime.now(timezone.utc)
    attr_text = (
        "<b>Fonte / Source:</b> INPE — DETER · BDQueimadas · PRODES<br/>"
        f"<b>Coleta / Collection:</b> {ts.strftime('%Y-%m-%d %H:%M UTC')}<br/>"
        "Dados públicos INPE — uso livre com atribuição."
    )
    story.append(Paragraph(attr_text, muted_style))
    story.append(Spacer(1, 0.6*cm))

    # Chart image (kaleido required for Plotly → PNG)
    if chart is not None:
        try:
            img_bytes = chart.to_image(format="png", width=700, height=380, scale=2)
            story.append(Image(io.BytesIO(img_bytes), width=16*cm, height=8.7*cm))
            story.append(Spacer(1, 0.6*cm))
        except Exception:
            story.append(Paragraph("<i>Gráfico não disponível / Chart not available.</i>",
                                   muted_style))
            story.append(Spacer(1, 0.4*cm))

    # Data table (max 50 rows to keep PDF size reasonable)
    if not df.empty:
        rows_to_show = df.head(50)
        header = [str(c) for c in rows_to_show.columns.tolist()]
        table_data = [header] + [
            [str(v) for v in row] for row in rows_to_show.itertuples(index=False)
        ]
        col_width = (16 * cm) / len(header)
        tbl = Table(table_data, colWidths=[col_width] * len(header))
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E7A4A")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, 0), 9),
            ("FONTSIZE", (0, 1), (-1, -1), 8),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F4F9F6")]),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#D4E6DA")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        story.append(tbl)
        if len(df) > 50:
            story.append(Spacer(1, 0.3*cm))
            story.append(Paragraph(
                f"<i>Mostrando 50 de {len(df)} linhas / Showing 50 of {len(df)} rows.</i>",
                muted_style,
            ))

    doc.build(story)
    return buf.getvalue()


# ------------------------------------------------------------------ #
# PDF — plain-text fallback (no reportlab)                              #
# ------------------------------------------------------------------ #

def _pdf_fallback(
    df: pd.DataFrame,
    title: str,
    fetched_at: datetime | None,
) -> bytes:
    """Minimal PDF without reportlab: plain text wrapped in a PDF envelope."""
    lines = [title, ""]
    for line in _attribution_block(fetched_at):
        lines.append(line.lstrip("# "))
    lines.append("")
    if not df.empty:
        lines.append(df.to_string(index=False))

    content = "\n".join(lines).encode("latin-1", errors="replace")

    # Minimal valid PDF 1.4 wrapping the text as a stream
    stream = (
        b"BT\n/F1 10 Tf\n50 750 Td\n"
        + b"(" + content[:2000].replace(b"(", b"\\(").replace(b")", b"\\)") + b") Tj\n"
        + b"ET"
    )
    objects = [
        b"%PDF-1.4\n",
        b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
        b"2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
        b"3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842]\n"
        b"   /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n",
        b"4 0 obj\n<< /Length " + str(len(stream)).encode() + b" >>\nstream\n"
        + stream + b"\nendstream\nendobj\n",
        b"5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
    ]
    body = b"".join(objects)
    xref_offset = len(body)
    xref = (
        b"xref\n0 6\n"
        b"0000000000 65535 f \n"
        + b"".join(
            f"{sum(len(o) for o in objects[:i]):010d} 00000 n \n".encode()
            for i in range(1, 7)
        )
    )
    trailer = (
        b"trailer\n<< /Size 6 /Root 1 0 R >>\n"
        b"startxref\n" + str(xref_offset).encode() + b"\n%%EOF\n"
    )
    return body + xref + trailer
