"""alert status fields

Revision ID: 0c4d7be20853
Revises: dd575ba70d24
Create Date: 2026-06-09 15:13:45.186766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0c4d7be20853'
down_revision: Union[str, None] = 'dd575ba70d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'updated_at')
    # ### end Alembic commands ###
