"""initial schema

Revision ID: dd575ba70d24
Revises: 
Create Date: 2026-05-25 12:48:35.476357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dd575ba70d24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity_level', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=64), nullable=True),
    sa.Column('biome_id', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('detection_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('affected_area_km2', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_id'), 'alerts', ['alert_id'], unique=True)
    op.create_index(op.f('ix_alerts_detection_date'), 'alerts', ['detection_date'], unique=False)
    op.create_index(op.f('ix_alerts_severity_level'), 'alerts', ['severity_level'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('langfuse_session_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_sessions_session_id'), 'conversation_sessions', ['session_id'], unique=True)
    op.create_table('environmental_data_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cache_source_query', 'environmental_data_cache', ['source', 'query_hash'], unique=False)
    op.create_index(op.f('ix_environmental_data_cache_cache_key'), 'environmental_data_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_environmental_data_cache_expires_at'), 'environmental_data_cache', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_environmental_data_cache_expires_at'), table_name='environmental_data_cache')
    op.drop_index(op.f('ix_environmental_data_cache_cache_key'), table_name='environmental_data_cache')
    op.drop_index('ix_cache_source_query', table_name='environmental_data_cache')
    op.drop_table('environmental_data_cache')
    op.drop_index(op.f('ix_conversation_sessions_session_id'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity_level'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_detection_date'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
